### ISSUE TITLE
Working Group page updates

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#1002]
- [x] @aeiras this section needs the program plan for 2025 https://microprofile.io/workinggroup/#mptab-program-plan-budget

- [x] Remove most popular topics title
- [x] members onboarding "process" > remove "Process"
- [x] remove slack from social media section

**Comment by rstjames** [comment]
@aeiras if this is ready to be updated let me know and I will change out the content.

**Comment by aeiras** [comment]
@rstjames it looks good. 

The 2025 program and budget has been updated here: https://drive.google.com/drive/folders/1n-4iMr-elQBhCN9YIaRVtUCwV4tqqqqs

I think it has all the documents you need to update the section.

**Comment by rstjames** [comment]
@aeiras I will need to have editing access to the program plan slides to be able to embed it on the website.

**Comment by rstjames** [comment]
got access from John @aeiras

**Comment by aeiras** [comment]
@rstjames I have downloaded the document to the community drive https://drive.google.com/drive/folders/1WzEjYfe4Pvj-cl_zPwWlyrEv_A8qwSiG. 

The current drive is external and managed by the EF. John cannot give you the correct access to adjust it. 

Please let me know if that fixes the issue.  Also added the PPT here just in case. 
[2025 MicroProfile Program Plan.pptx](https://github.com/user-attachments/files/18101343/2025.MicroProfile.Program.Plan.pptx)

**Comment by rstjames** [comment]
@aeiras John gave me access and all is updated on the wg page. Thank you.
