### ISSUE TITLE
[New MPWG Guest Member Announcement] Ostfalia University ]

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#1005]
Ostfalia University - Guest member needs to be added to MP.io. [New Members' guidelines](https://github.com/microprofile/microprofile-wg/wiki/MicroProfile-Working-Group:--New-Members-Onboarding-Guidelines)
Bernd Müller and Kai Gutenschwager (Ostfalia University of Applied Sciences, Faculty of Computer Science)
[Re: [microprofile-wg] [microprofile] Fwd: Welcome Ostfalia University as a Guest Member of the Jakarta EE Working Group and MicroProfile Working Group as well!](https://www.eclipse.org/lists/microprofile-wg/msg02644.html)
 Bernd Müller - MPWG Introductory Message
 
 @Emily-Jiang 

- [x] contact Ostfalia University 
- [x] make sure they are set up on github
- [x] provided logo for website 
- [x] website and contact for the working group page

**Member**
Name
Twitter ID 
Organization logo

**Website**
URL

**Media Description**
280 characters max
includes the members Twitter ID, website in the absence of blog annoucement written by the member. 

**Design Card** (for MicroProfile designer)

**Notes**
To help with everything

**Comment by BerndMuller** [comment]
# Member
- Ostfalia University, Faculty of Computer Science
-  not on Twitter
- [logo link](https://www.ostfalia.de/export/system/modules/de.ostfalia.module.template/resources/images/logo/Ostfalia_German.png_230952558.png)

# Website
[Ostfalia, Computer Science](https://www.ostfalia.de/cms/de/i/)

# Media Description
The Faculty of Computer Science has existed for 30 years and has grown continuously with 24 professors and over 1000 students. Our range of courses includes courses that require typical on-campus study as well as courses that are offered in a purely online format. At the Faculty of Computer Science one can study five Bachelor programs and two Master degree programs. The online format offers two Bachelor and two Master degree programs.

**Comment by aeiras** [comment]
Hola @BerndMuller, good to see you here. Welcome! :) 

This sheet https://docs.google.com/spreadsheets/d/1QflmI_5NWLEGDGImibvMx5iSFUZisbnHjMvvOIcLRy0/edit?gid=1552728526#gid=1552728526 has not been updated with your information yet. Please contact the EMO and ask them to add you to the list as a guest member. 

@rstjames will follow up with you if anything else is needed. Cheers!

**Comment by BerndMuller** [comment]
Dear Amelia,

probably not updated because Ostfalia University is a guest member and - from my point
of view - not a member of the working group steering committee

If guest ARE member of the steering committee:
Organization: Ostfalia University
Representative: Bernd Müller
Alternate: Kai Gutenschwager

Regards

Bernd

Am 11.12.24 um 20:44 schrieb Amelia Eiras:
> Hola @BerndMuller <https://github.com/BerndMuller>, good to see you here. Welcome! :)
> 
> This sheet https://docs.google.com/spreadsheets/d/1QflmI_5NWLEGDGImibvMx5iSFUZisbnHjMvvOIcLRy0/edit? 
> gid=1552728526#gid=1552728526 <https://docs.google.com/spreadsheets/ 
> d/1QflmI_5NWLEGDGImibvMx5iSFUZisbnHjMvvOIcLRy0/edit?gid=1552728526#gid=1552728526> has not been 
> updated with your information yet. Please contact the EMO and ask them to add you to the list as a 
> guest member.
> 
> @rstjames <https://github.com/rstjames> will follow up with you if anything else is needed. Cheers!
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/eclipse/microprofile-marketing/ 
> issues/1005#issuecomment-2536963062>, or unsubscribe <https://github.com/notifications/unsubscribe- 
> auth/ 
> ACVBIVXIUTHD7THM2SW5XSD2FCIYLAVCNFSM6AAAAABTK7L6TOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMZWHE3DGMBWGI>.
> You are receiving this because you were mentioned.Message ID: <eclipse/microprofile-marketing/ 
> ***@***.***>
> 


-- 
Prof. Dr. Bernd Müller

Ostfalia
Hochschule für angewandte Wissenschaften
- Hochschule Braunschweig/Wolfenbüttel -
Fakultät Informatik
Salzdahlumer Straße 46/48
38302 Wolfenbüttel

Tel  +49 5331 939 31160
Fax  +49 5331 939 31004
Web  www.ostfalia.de / www.pdbm.de

**Comment by aeiras** [comment]
True that Guest members have no voting rights under the Working Group, however your Organization and representatives are added in the MP website under the working group page, now updated thanks to your prompt response and @rstjames' dedication. 

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/df366a0a-f853-484d-8ded-8b0d3af5158e" />

Wishing you Happy Holidays and do expect MP social media to highlight Ostfalia University support for OSS and MP community.  

---

@rstjames, when can we expect MP Hootsuite (MP Twitter, MP FB and MP LinkedIn) to share the new member post?  Thank you for using this ticket to update @BerndMuller.

**Comment by rstjames** [comment]
I am solving one technical issue to get Ostfalia University logo on the website and after I solve this I will schedule the social media announcement  @aeiras

**Comment by rstjames** [comment]
🌟 Exciting News! 🌟
Join us in giving a warm welcome to Ostfalia University, Faculty of Computer Science, as the newest Guest Member of the MicroProfile Working Group! 🎉

Welcome to the MicroProfile family! 💻✨

#MicroProfile #OpenSource #EnterpriseJava #Community 
![micprofile_new_wg_guest_membe_Ostfalia University](https://github.com/user-attachments/assets/790f4b8d-9ff3-4003-900a-b7eaca179cca)


If there are no objections, it will go out tomorrow and 2nd week of Jan. @aeiras @Emily-Jiang @BerndMuller
