### ISSUE TITLE
  December 9th 25th 2024 MicroProfile AI video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#1007]
Here is the [link to the video](https://drive.proton.me/urls/VRSBYDQ70C#pTOOa2oCxvOj) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/14kSPRzEb0_BXrow1ej7Z6cus23uWypR_NcoegimJaBA/edit?tab=t.0#bookmark=kix.bzrm831gnv57) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
Updated
