### ISSUE TITLE
December 9th 2024 MicroProfile Marketing video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#1008]
Here is the [link to the video](https://drive.proton.me/urls/AKKD3PRTN8#v1VIl9XBFFzq) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1IEuuIowvv5epov_rNLva51IjRMgUGlbfPi-lInecJRI/edit?tab=t.0#bookmark=id.jmq7lub5f6xn) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
Update https://youtu.be/omyfB6XI3_A
