### ISSUE TITLE
[OC1 media design] requires fixing when seen on a cell it cuts logos

### ISSUE THREAD

**Issue by aeiras** [eclipse/microprofile-marketing#194]
![IMG_4531](https://user-images.githubusercontent.com/10731224/64805515-16e45300-d546-11e9-8025-bae71aa3ae89.PNG)

**Comment by rstjames** [comment]
@aeiras this tweet have been fixed and I adjusted 2 others so they should fit better when they go out next week. I will keep this same formate for any other tweets I put out next for mp.

**Comment by aeiras** [comment]
You are amazing MicroProfile @rstjames 💛 thank YOU for prompt fix & scaling it to future tweets.
