### ISSUE TITLE
[Blog Contribution] MicroProfile 6.1 support and MicroProfile OpenAPI updates in Open Liberty 23.0.0.12

### ISSUE THREAD

**Issue by lauracowen** [eclipse/microprofile-marketing#884]
**[MicroProfile.io WordPress](https://microprofile.io/wp-admin/post.php?post=7351&action=edit)**
 
 **Social Media Description**
 - [x]  MicroProfile 6.1 implementation in @OpenLibertyIO 23.0.0.12 includes stats configuration in MP Metrics 5.1, and the latest Open Telemetry updates in MP Telemetry 1.1.

 **Design Card**  (for MicroProfile designer)
 - [x]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by emecas** [comment]
@aeiras  for WordPress review?  

if so then , @lauracowen my comments to the suggestion in WordPress

- _Outbound links: No outbound links appear in this page._ 
    -----> Even the full entry has a link to https://openliberty.io/blog/2023/12/12/23.0.0.12.html could you try by embedded the link in one specify section in the text?
- _Internal links: No internal links appear in this page,_  
    ----> Is no a chance to link an old entry about "previous releases" or "see also" ?
- _Keyphrase length: No focus keyphrase was set for this page._  
    -----> I added same than title "MicroProfile 6.1 support and MicroProfile OpenAPI updates in Open Liberty 23.0.0.12" , but they suggest make it shorted and using synonyms 
- _Meta description length: No meta description has been specified._ 
    -------> I added title  here, but nos sure if that is ideal, thy suggest align to the Keyphrase 
- _Text length: The text contains 63 words. This is far below the recommended minimum of 300 words. Add more content._ 
    -----> it is possible to summarize the sections from the external link !!!
- _SEO title width: The SEO title is wider than the viewable limit. Try to make it shorter._
    ------> !!!!

**Comment by lauracowen** [comment]
@emecas Hi, thanks for taking a look. I followed the [Case 2 instructions](https://github.com/microprofile/wpsite#case-2-if-blog-post-is-a-redirect-to-another-url-post-content-is-not-hosted-at-wp-mpio). The text in the editor isn't intended to appear as a post in its own right, it only appears on the main https://microprofile.io/blog/ page. The link to the post then redirects to the post as hosted on openliberty.io. It's not relevant, therefore, to have outbound and internal links.

I've added SEO title and SEO description to the post, though I'm not sure how Google sees the post when it's not hosted directly on the MP website. I don't know if Google just takes text from the Wordpress summary, or if it looks at the full post. Anyway, it won't do any harm to have those entries filled in. If this is something that's known to be useful even for Case 2 blog posts, I can update the wiki instructions to add that step.

**Comment by emecas** [comment]
@lauracowen my apologies for the confusion! Being away from the review process for so long has definitely made me rusty. I was interested in a more in-depth SEO analysis and suggestions tailored specifically for regular blog posts.

I appreciate the offer to update the Wiki, but I believe we need a thorough discussion to determine which points from the SEO analysis are applicable to the Case 2 instructions, considering that even short blog posts can benefit from several SEO strategies (Option 2 - Redirect Post).

Same for #885 

For now here are the validations criteria: Approved and published 

Permalink: [MicroProfile 6.1 support and MicroProfile OpenAPI updates in Open Liberty 23.0.0.12](https://microprofile.io/2024/03/01/microprofile-6-1-liberty-23-0-0-12/)

Added tags:  `announcements`  `MicroProfile 6.1`  `Open Liberty`  `OpenAPI`  `Tools`

- [x]  Ensure the content of post is relevant and applicable to Microprofile
- [x]  Check that content has the author(s) name
- [x]  Check that the content provides credit to collaborators
- [x]  Check that post has a “Page Header Image”
- [ ]  The image should be between 1600px - 2000px wide and have a minimum height of 500px for best results.
        mpmetrics51.png February 29, 2024 296 KB 3214 by 1086 pixels 
- [x]  Check for grammatical errors
- [x]  Check for TMs and copyrights

**Comment by rstjames** [comment]
![microprofile_MicroProfile-6 1_implementation_OpenLibertyIO](https://github.com/eclipse/microprofile-marketing/assets/12132146/c33df205-5d4e-4f5f-96cc-d98634ad8fe7)

**Comment by rstjames** [comment]
scheduled
