### ISSUE TITLE
[Blog Contribution] Negative acknowledgment and more for MicroProfile Reactive Messaging in Open Liberty 24.0.0.2

### ISSUE THREAD

**Issue by lauracowen** [eclipse/microprofile-marketing#885]
**[MicroProfile.io WordPress](https://microprofile.io/wp-admin/post.php?post=7353&action=edit)**

 **Social Media Description**
 - [x]  Negative acknowledgement is introduced to MicroProfile Reactive Messaging in @OpenLibertyIO 24.0.0.2 release. New "nack" support can send or handle events re problems with the payload or exceptional behaviour.

 **Design Card**  (for MicroProfile designer)
 - [x]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by emecas** [comment]
@lauracowen my comments to the suggestions in WordPress

 -  Outbound links: No outbound links appear in this page.
    -----> Even the full entry has a link to https://openliberty.io/blog/2024/02/27/24.0.0.2.html could you try by embedded the link in one specify section in the text?
 -  Internal links: No internal links appear in this page,
    ----> Is no a chance to link an old entry about "related definitions" like `negative acknowledgment` or  `emitters  backpressure support`  or ` integration tests` or "see also"  links?
-  Keyphrase length: No focus keyphrase was set for this page.
    -----> I added same than title "Negative acknowledgment and more for MicroProfile Reactive Messaging in Open Liberty 24.0.0.2" , but they suggest make it shorted and using synonyms
 -  Meta description length: No meta description has been specified.
    -------> I added title here, but I am not sure if that is ideal, they suggest align to the Keyphrase
 - Text length: The text contains 76 words. This is far below the recommended minimum of 300 words. Add more content.
    -----> it is possible to summarize the sections from the external link !!!
 - SEO title width: The SEO title is wider than the viewable limit. Try to make it shorter.
    ------> !!!!

**Comment by lauracowen** [comment]
@emecas Hi, thanks for taking a look. I followed the [Case 2 instructions](https://github.com/microprofile/wpsite#case-2-if-blog-post-is-a-redirect-to-another-url-post-content-is-not-hosted-at-wp-mpio). The text in the editor isn't intended to appear as a post in its own right, it only appears on the main https://microprofile.io/blog/ page. The link to the post then redirects to the post as hosted on openliberty.io. It's not relevant, therefore, to have outbound and internal links.

I've added SEO title and SEO description to the post, though I'm not sure how Google sees the post when it's not hosted directly on the MP website. I don't know if Google just takes text from the Wordpress summary, or if it looks at the full post. Anyway, it won't do any harm to have those entries filled in. If this is something that's known to be useful even for Case 2 blog posts, I can update the wiki instructions to add that step.

**Comment by emecas** [comment]
@lauracowen  

Approved and published 

Permalink: [Negative acknowledgment and more for MicroProfile Reactive Messaging in Open Liberty 24.0.0.2](https://microprofile.io/2024/03/01/negative-acknowledgment-and-more-for-microprofile-reactive-messaging-in-open-liberty-24-0-0-2/)

Added tags:   `Release`  `microprofile`  `Reactive`  `Open Liberty`  Release `Messaging`  `Streams Operators`

- [x]  Ensure the content of post is relevant and applicable to Microprofile
- [x]  Check that content has the author(s) name
- [x]  Check that the content provides credit to collaborators
- [x]  Check that post has a “Page Header Image”
- [ ]  The image should be between 1600px - 2000px wide and have a minimum height of 500px for best results.
        reactive-nack.png February 29, 2024 303 KB 3214 by 1086 pixels 
- [x]  Check for grammatical errors
- [x]  Check for TMs and copyrights

**Comment by rstjames** [comment]
scheduled 
![microprofile-MicroProfile-Reactive-Messaging-in-Open-Liberty](https://github.com/eclipse/microprofile-marketing/assets/12132146/353e6ca1-8fa8-4183-b2ae-4b5125c3fb18)
