### ISSUE TITLE
[Documentation ] e-Ballot - Yearly Printing Wearable Swag: Email to MPWG

### ISSUE THREAD

**Issue by aeiras** [eclipse/microprofile-marketing#888]
Located under the MPWG external drive: [Ballots](https://drive.google.com/drive/folders/1d9rK1UL-NVMlO7dZzBdOMiPTVaZPPXv9)

@emecas thanks for the addition review for sending the ballot, MicroProfiler!

[e-Ballot - Yearly Printing Wearable Swag: Email to MPWG](https://docs.google.com/document/d/1_buMxbNWoiV63EpQbv--s-Phnstrsuo5mcUgpNzRATc/edit#heading=h.f8r8csevkao1)

<img width="936" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/53a8d457-85eb-4621-83d6-973efa78bafe">

**Comment by emecas** [comment]
Thanks @aeiras  , template LGTM, I will be sending the ballot in short!!!

**Comment by emecas** [comment]
03/05/2024 - Prepared and sent ballot to MP-WG for voting design as:
[microprofile-wg] [e-BALLOT] 2024 Printing Wearable Swag- VOTE by 12th March
https://www.eclipse.org/lists/microprofile-wg/msg02355.html

**Comment by aeiras** [comment]
ballot sent
