### ISSUE TITLE
[MPWG Page and landing page]  Add the Guest Member as a membership category 

### ISSUE THREAD

**Issue by aeiras** [eclipse/microprofile-marketing#889]
@rstjames, 

There are 3 places where the Members are listed on the MPWG page. https://microprofile.io/workinggroup/#

1. create a sub-division under the listed logos to highlight Guest Members
<img width="1214" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/c281e201-9d8b-469b-9bcb-7d2e024de62a">

2. duplicate the above and copy it to the landing page listing of Members https://microprofile.io 

3. Under https://microprofile.io/workinggroup/#mptab-members, please create the sub-category below to enable the listing of Guest Members

**Guest Members**
As stated in the MicroProfile Working Group [Charter](https://www.eclipse.org/org/workinggroups/microprofile-charter.php), it is the sole prerogative of the Steering Committee to invite Organizations to contribute as Guest Members to the Working Group. The invite is valid for the MP year and secured via an e-ballot through the MPWG mailing list. The Guest Members pay no annual fees and have no voting rights. 

Organization    Representative        Alternate

----
questions, shoot and thank you!

**Comment by rstjames** [comment]
@aeiras None of this has been voted on, correct? 

1. This will look very strange and unbalanced if one logo is added under the rest of them. 
2. These logos are on the home page already; would you like to move them up on the page? 
3. I will do this when all voting is done.

**Comment by aeiras** [comment]
correct, @rstjames. This is the work ahead after the vote is completed. 
There is always some thinking needed when adjusting the current page. Ticket ahead of time to enable you to figure out a good way to do the changes. Cheers.

**Comment by rstjames** [comment]
logo has been added back with "guest member " label.  @aeiras 

I have not added back to the table; I can not find what people should be listed there. Sorry I deleted it and forgot to record what it was.

**Comment by aeiras** [comment]
@rstjames, 

Good job adding the Guest Member underneath the organization logo. It works great, quite scalable. 

GSJUG primary is: Michael Redlich

**Comment by rstjames** [comment]
@Dexmaster can you please add his Twitter Linked icon to this page "Michael Redlich" https://twitter.com/mpredli?lang=en

**Comment by rstjames** [comment]
A
<img width="904" alt="Screenshot 2024-03-14 at 10 44 27" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/2499ca2e-9be8-4f7b-8e1b-58fd9eea25b4">
ll updated

**Comment by aeiras** [comment]
> @rstjames,
> 
> There are 3 places where the Members are listed on the MPWG page. https://microprofile.io/workinggroup/#
> 
> 1. create a sub-division under the listed logos to highlight Guest Members
> 
> <img alt="image" width="1214" src="https://private-user-images.githubusercontent.com/10731224/309940806-c281e201-9d8b-469b-9bcb-7d2e024de62a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzE4MzAsIm5iZiI6MTcxMDQzMTUzMCwicGF0aCI6Ii8xMDczMTIyNC8zMDk5NDA4MDYtYzI4MWUyMDEtOWQ4Yi00NjliLTliY2ItN2QyZTAyNGRlNjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE1NTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3Nzk3ZjYwMWFiYWFhN2RjMWI0ZjdhZGM1ZjU1OWFkNmQwOTQwMzhjMWVmNjdkMjI5ZTRjNzdkYjJkZDQ0ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ivbS5oFgWflnKznxFMvTacUMHA3EaP0yQMEdUowrkUc">
> 2. duplicate the above and copy it to the landing page listing of Members https://microprofile.io
> 3. Under https://microprofile.io/workinggroup/#mptab-members, please create the sub-category below to enable the listing of Guest Members
> 
> **Guest Members** As stated in the MicroProfile Working Group [Charter](https://www.eclipse.org/org/workinggroups/microprofile-charter.php), it is the sole prerogative of the Steering Committee to invite Organizations to contribute as Guest Members to the Working Group. The invite is valid for the MP year and secured via an e-ballot through the MPWG mailing list. The Guest Members pay no annual fees and have no voting rights.
> 
> Organization Representative Alternate
> 
> questions, shoot and thank you!

@rstjames, 

The issue is re-opened. 

Please check this ticket. A new category is a must; the write-up is already in this ticket. 

Thanks for working on this.

**Comment by rstjames** [comment]
Updated 
<img width="962" alt="Screenshot 2024-03-15 at 13 23 23" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/c6d6c150-000c-4bd1-85cb-59e2d64abaf2">

**Comment by aeiras** [comment]
The new Guest members section looks great, @rstjames! Thank you.
