### ISSUE TITLE
Regarding Using an Image about MicroProfile Releases in MicroProfile Tutorial

### ISSUE THREAD

**Issue by ttelang** [eclipse/microprofile-marketing#892]
Hi Amelia, 

I want to use this image about Microprofile releases in MicroProfile Tutorial. 
https://jakarta.ee/news/developer-guide-for-jakarta-ee-10-and-microprofile-6.0/images/microprofile-releases.jpg

The image is from posted on this blog post.
https://jakarta.ee/news/developer-guide-for-jakarta-ee-10-and-microprofile-6.0/

Please check and revert back whether it is ok to use this from the licensing / copyright perspective. 
 
Best Regards
Tarun

**Comment by rstjames** [comment]
I believe this is Emily's blog. Please write here. 
@Emily-Jiang is this ok to use?

**Comment by Emily-Jiang** [comment]
> I believe this is Emily's blog. Please write here. @Emily-Jiang is this ok to use?

yes, of course.

**Comment by rstjames** [comment]
@ttelang, did you see the reply from Emily? 

If so lets close this ticket please

**Comment by rstjames** [comment]
@ttelang I am going to close this ticket
