### ISSUE TITLE
MicroProfile API Javadoc for top level umbrella specification

### ISSUE THREAD

**Issue by ttelang** [eclipse/microprofile-marketing#893]
MicroProfile API Javadoc - https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html. 

The above link is provided by Open Liberty.  

Is there any corresponding javadoc link for the top level umbrella specification microProfile 6.1 which has MicroProfile.io or eclipse / javadoc.io as the top level domain?

**Comment by rstjames** [comment]
@Emily-Jiang do you have the answer for this? It is from March...

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang do you have the answer for this? It is from March...

https://www.javadoc.io/doc/org.eclipse.microprofile/microprofile/5.0/index.html
6.0 and 6.1 javadoc was not produced due to an error. I'll see whether we can do a service release to get it fixed. MP 7.0 should be able to produce a javadoc.
