### ISSUE TITLE
[2024 Yearly Social Media] MPWG Quotes- Guidelines Submit 

### ISSUE THREAD

**Issue by emecas** [eclipse/microprofile-marketing#895]
Inventory sheet **[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1667854410)**

**Media Description**

#WordOnTheStreet: What's your @MicroProfileIO quote? Submit it & tell us why you ❤️ devoting your time to #MicroProfileTechnology!  [microprofile.io/workinggroup/#testimonials]  #ByCommunityForCommunity #SharingIsCaring  #OpenSource  [bit.ly/submit-quote]

**Time**

1 workday

**Schedule**

1 month

**Design Card**

**Notes**

  2022 issue: https://github.com/eclipse/microprofile-marketing/issues/662

  2023 issue: https://github.com/eclipse/microprofile-marketing/issues/765

**Comment by rstjames** [comment]
scheduled: 
![microprofile_quote_2024](https://github.com/eclipse/microprofile-marketing/assets/12132146/29e62f6a-f5d3-45c2-b082-688f3b4deb72)

**Comment by rstjames** [comment]
![microprofile_quote_2024](https://github.com/eclipse/microprofile-marketing/assets/12132146/4eaefed7-f813-4822-96f1-ca6e027a59e6)
scheduled:

**Comment by emecas** [comment]
@rstjames  there is something that does not fit :

![image](https://github.com/eclipse/microprofile-marketing/assets/849502/70badc83-f337-4ade-aa50-4e2b1f4bfa52)

**Comment by rstjames** [comment]
@emecas good catch. Updated the typo and improved the text 
![microprofile_quote_2024](https://github.com/eclipse/microprofile-marketing/assets/12132146/1ed3a243-2cde-4fd7-9480-cbf9939f150c)

**Comment by emecas** [comment]
Great Job @rstjames. Thanks 

When is this scheduled for? I mean do you know when will be the sooner next print?

**Comment by rstjames** [comment]
@emecas first week of every month. I believe it goes out tomorrow

**Comment by emecas** [comment]
04/05/2024 https://twitter.com/MicroProfileIO/status/1776112647756206314
