### ISSUE TITLE
March 19th 2024 MicroProfile AI video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#896]
Here is the [link to the video](https://drive.proton.me/urls/9VPT5FGBFR#wLqkzW1HU5ag) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/14kSPRzEb0_BXrow1ej7Z6cus23uWypR_NcoegimJaBA/edit#bookmark=id.hup972f0ra9l) with a link to the recording.

Please add this video to a "MicroProfile AI" playlist.

Thanks!

**Comment by rstjames** [comment]
Updated
