### ISSUE TITLE
March 19th 2024 MicroProfile Steering Committee video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#898]
Here is the [link to the video](https://drive.proton.me/urls/WQK25V55ZW#VX5PHpACuwNA) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/14Yuez5l5lYctcMt-216So5Ouboh0PqturSAJn3B0KE4/edit#heading=h.hyh98usp6p0d) with a link to the recording.

Please add this video to a "MicroProfile AI" playlist.

Thanks!

**Comment by rstjames** [comment]
@jclingan don't have access to update meeting notes https://youtu.be/mTWEkJsEnIg
