### ISSUE TITLE
[Social Media] Tweet about MicroProfile AI

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-marketing#900]
**Schedule**
Monday
3:00PM GMT

**Media Description**
MicroProfile enters AI. A few MicroProfilers got together on Mondays at 3:00pm GMT at a weekly basis to work on the MicroProfile AI specification. You can find the joining details from [here](https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=GMT&pli=1). Please join us.

**Design Card** (for MicroProfile designer)
Minimal requirements highlight the MicroProfiler & the Organizers

**Notes**
To help with everything

**Comment by rstjames** [comment]
![Microprofile_ai_call_2024](https://github.com/eclipse/microprofile-marketing/assets/12132146/a5662426-5ae7-4c55-9b32-9b4081b177d3)

**Comment by rstjames** [comment]
scheduled
