### ISSUE TITLE
April 15th 2024 MicroProfile Marketing video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#902]
Here is the [link to the video](https://drive.proton.me/urls/P38QEDJ84C#d3RlhFCd4PVQ) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1IEuuIowvv5epov_rNLva51IjRMgUGlbfPi-lInecJRI/edit#bookmark=id.hzscom233rv0) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
Updated
