### ISSUE TITLE
[MPWG Page]  WG Member Primeton is duplicated in the website

### ISSUE THREAD

**Issue by emecas** [eclipse/microprofile-marketing#904]
[Primeton](https://www.primeton.com/english/) line in  https://microprofile.io/workinggroup/ is twice

![image](https://github.com/eclipse/microprofile-marketing/assets/849502/00a10bdc-b82a-43d5-8887-bd8198c8aaab)

**Comment by rstjames** [comment]
updated 
<img width="932" alt="Screenshot 2024-04-18 at 8 53 17" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/a9628e7e-e446-4bb3-b9db-4c7511d8e16f">
