### ISSUE TITLE
April 23rd 2024 MicroProfile Technical Meeting video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#908]
Here is the [link to the video](https://drive.proton.me/urls/458KDY9MPW#sjvNIC1i8VgB) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1hzEhePFbZ_9d5Nm-DdK-Coilm1J309GH82Yb8_hgB50/edit#bookmark=kix.jq047eglwbit) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
Link to video does not work @jclingan

**Comment by jclingan** [comment]
Fixed

**Comment by rstjames** [comment]
Updated
