### ISSUE TITLE
April 29th 2024 MicroProfile Marketing video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#910]
Here is the [link to the video](https://drive.proton.me/urls/JM4GTKP5JC#5z2UcBUBBteu) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1IEuuIowvv5epov_rNLva51IjRMgUGlbfPi-lInecJRI/edit#bookmark=kix.spg5rkf40d26) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://youtu.be/hnPEf3feqNU
uploaded
