### ISSUE TITLE
[2024 Yearly Social Media] Speakers Highlight  Call to Action

### ISSUE THREAD

**Issue by emecas** [eclipse/microprofile-marketing#912]
Inventory sheet **[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1667854410)**

**Media Description**

#MicroProfileSpeakers: Are you giving a #MicroProfile session or talk? If YES, your session needs global social media (Twitter, Facebook & LinkedIn) coverage!

Get  support by MicroProfile Community here: https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support

#OpenSource

**Schedule**
2  per month
 - workday
 - weekend day

**Notes**

2022 issue
https://github.com/eclipse/microprofile-marketing/issues/670

2023 issue
https://github.com/eclipse/microprofile-marketing/issues/769

**Comment by rstjames** [comment]
![microprofile_session](https://github.com/eclipse/microprofile-marketing/assets/12132146/a0071b61-766f-4208-aef1-5c52d94998c9)

**Comment by rstjames** [comment]
scheduled on hootsuite
