### ISSUE TITLE
[2024 Yearly Social Media] Content / Blog Contributions

### ISSUE THREAD

**Issue by emecas** [eclipse/microprofile-marketing#913]
Inventory sheet **[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1667854410)**

**Media Description**

#SharingIsCaring Have you shared your #MicroProfile knowledge with @MicroProfileIO? Become a MicroProfile Author. Contribute with your blogs :memo:, videos :clapper:, ideas :bulb:, recordings :microphone:, tutorials :page_with_curl:, experiments :test_tube:, books :books:, sessions :satellite:, events :date:. Visit and Join the community: https://microprofile.io/blog/

#ByCommunityForCommunity

**Schedule**

2 per month

**Notes**

2023 Issue
https://github.com/eclipse/microprofile-marketing/issues/768

2022 Issue
https://github.com/eclipse/microprofile-marketing/issues/669

**Comment by aeiras** [comment]
@emecas this is so cute! 

I recommend it gets post it twice a month. 1 is not enough.

**Comment by emecas** [comment]
Updated !!!

**Comment by rstjames** [comment]
![microprofile_contribute](https://github.com/eclipse/microprofile-marketing/assets/12132146/2e3df671-c049-407e-ba80-7aaa8c0f3665)

**Comment by rstjames** [comment]
Updated and scheduled

**Comment by emecas** [comment]
05/20/2024 https://x.com/MicroProfileIO/status/1792435258538823973
