### ISSUE TITLE
[2024 Yearly Social Media] Victor O @Tuxtor Spanish Videos 

### ISSUE THREAD

**Issue by emecas** [eclipse/microprofile-marketing#914]
Inventory sheet **[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1667854410)**

**Media Description**

#MicroProfileVideoTutoriales: ¿Estas iniciando una aplicación con #microservicios y Java? ¿Sabes que es MicroProfile? En los Videotutoriales: Recorriendo MicroProfile en Español @tuxtor te ayuda a explorar el camino #CloudNative con #Java y #MicroProfile

https://microprofile.io/2021/09/01/videotutoriales-recorriendo-microprofile-en-espanol/

#OpenSource #Spanish

**Schedule**
1 per month

**Design Card**
Minimal requirements

**Notes**

2022 Issue 
https://github.com/eclipse/microprofile-marketing/issues/668

**Comment by rstjames** [comment]
![microprofile_spanish_videos](https://github.com/eclipse/microprofile-marketing/assets/12132146/43e2b4bb-314b-48a6-b114-7ad8c1446f3f)

**Comment by rstjames** [comment]
![microprofile_video-tutoriales](https://github.com/eclipse/microprofile-marketing/assets/12132146/60ed4f61-c6a7-44eb-8c86-468f298c5dbe)

Scheduled
