### ISSUE TITLE
[2024 Yearly Social Media] Yearly Project Plan & Budget

### ISSUE THREAD

**Issue by emecas** [eclipse/microprofile-marketing#916]
Inventory sheet **[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1667854410)**

**Media Description**

MicroProfile provides :loudspeaker: 100% #Transparency & #Openness :100: :open_book: :mag: on its money expenditures. Take a look of our Project Plan & Budget: ️ :construction:  :bar_chart: :moneybag: for 2024 : https://microprofile.io/workinggroup/#mptab-program-plan-budget  

**Schedule**

1 per month

**Notes**

No antecedent, first year

**Comment by rstjames** [comment]
scheduled once a month
![microprofile_project_plan](https://github.com/eclipse/microprofile-marketing/assets/12132146/1b0986fb-833e-4273-893a-a4eb2ef5aa4e)

**Comment by emecas** [comment]
05/07/2024 https://twitter.com/MicroProfileIO/status/1787784861253521412?t=NGbchFXG5zAy7Uv31IvjSg&s=19
05/09/2024 https://x.com/MicroProfileIO/status/1788448986090688533
