### ISSUE TITLE
May 7th 2024 MicroProfile Marketing video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#917]
Here is the [link to the video](https://drive.proton.me/urls/GPMP3588RW#JSBsudD3Ve1i) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1hzEhePFbZ_9d5Nm-DdK-Coilm1J309GH82Yb8_hgB50/edit#bookmark=kix.2cx0ko9qlr1v) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://www.youtube.com/watch?v=OJwbiN9xPRY

Updated
