### ISSUE TITLE
Conference: JCon Europe talk: Master the Cloud Native Application Standard: MicroProfile

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-marketing#918]
**[MP DevRel Branding Resources Community Support](https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support)**

**MicroProfiler**
Emily Jiang
Twitter ID: @emilyfhjiang  or Github ID: @Emily-Jiang 
Picture, nice to have
https://twitter.com/emilyfhjiang/photo

**Event**
Link to the event/conference/Session
https://2024.europe.jcon.one/

Organizer logo,  nice to have

**Schedule**
Day
Time
16.05.2024 02:30 PM - Cinema 7
**Media Description**
280 chararters
includes the Twitter ID of the Organizers & the name or Twitter ID of the speaker
If you are @jcon_conference , make sure to attend the session our #javachampion @emilyfhjiang to master the Cloud Native Standard @MicroProfileIO where she will tell you the latest and greatest about this technology with live demos.

**Design Card** (for MicroProfile designer)
Minimal requirements highlight the MicroProfiler & the Organizers

**Notes**
To help with everything

**Comment by rstjames** [comment]
Scheduled. 
![jcon_2024_microprofile_emily-jiang](https://github.com/eclipse/microprofile-marketing/assets/12132146/4be510c3-de81-4896-b17a-211963a99541)

**Comment by rstjames** [comment]
Scheduled 
![jcon_2024_microprofile_emily-jiang-2](https://github.com/eclipse/microprofile-marketing/assets/12132146/d17c8f11-8de6-471c-8c4d-bbaf65091351)
