### ISSUE TITLE
Conference: JCon Europe talk: AI-powered Java Developers

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-marketing#919]
**[MP DevRel Branding Resources Community Support](https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support)**

**MicroProfiler**
Emily Jiang
Twitter ID: @emilyfhjiang  or Github ID: @Emily-Jiang 
Picture, nice to have
https://twitter.com/emilyfhjiang/photo

**Event**
Link to the event/conference/Session
https://2024.europe.jcon.one/

**Schedule**
Day
Time
16th May 2024 ∙ 4:00-4:45

**Media Description**
280 chararters
includes the Twitter ID of the Organizers & the name or Twitter ID of the speaker

**Design Card** (for MicroProfile designer)
Minimal requirements highlight the MicroProfiler & the Organizers
#AI is a hot topic! What does AI bring for Java Developers? Our #Javachampion @emilyfhjiang will tell you all you need to know to be a AI-Powered Java Developers @jcon_conference on 16th May 4:00pm. Don't miss out!

**Notes**
To help with everything

**Comment by rstjames** [comment]
scheduled 
![jcon_2024_microprofile_emily-jiang](https://github.com/eclipse/microprofile-marketing/assets/12132146/8cbb75c0-a6e3-4a21-a4c7-88bae25fffe9)
