### ISSUE TITLE
[2024 Yearly Social Media]  Become a MPWG contributor/Member/User

### ISSUE THREAD

**Issue by emecas** [eclipse/microprofile-marketing#920]
Inventory sheet **[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1667854410)**

**Media Description**

Join the MicroProfile Working Group (MPWG) and be part of the future of Enterprise Java Microservices! ️☕️ The MPWG fosters a well-governed, vendor-neutral open  source ecosystem 🤝, Become a member and help shape its evolution &  sustainability  ➡️ https://microprofile.io/workinggroup/#prospectus

**Schedule**

1 per month

**Notes**

2023
https://github.com/eclipse/microprofile-marketing/issues/766

2022 
https://github.com/eclipse/microprofile-marketing/issues/664

**Comment by rstjames** [comment]
all scheduled 
![microprofile_working_group_2024](https://github.com/eclipse/microprofile-marketing/assets/12132146/6bdda5cb-8e2b-4d89-b704-68868a29ed36)
