### ISSUE TITLE
[2024 Yearly Social Media] MPWG Charter highlight

### ISSUE THREAD

**Issue by emecas** [eclipse/microprofile-marketing#921]
Inventory sheet **[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1667854410)**

**Media Description**

The MicroProfile Community 👷👷‍♀️🔧 owns the responsibility. Its Charter outlines: Limited processes, Experiment & innovate, Implementation first,  Encourage brand adoption, Openness. Transparency, inclusiveness, Low  barrier to entry.➡️ https://bit.ly/3bUh8lN  #OpenSource Specs

**Schedule**

1 per month

**Notes**

2023
https://github.com/eclipse/microprofile-marketing/issues/767

2022
https://github.com/eclipse/microprofile-marketing/issues/666

**Comment by rstjames** [comment]
![microprofile_charter_2024](https://github.com/eclipse/microprofile-marketing/assets/12132146/258608b0-b16e-4c83-a2f3-181b0d731e3e)
Scheduled
