### ISSUE TITLE
Reminder for Cloud Native Java Technical Survey

### ISSUE THREAD

**Issue by m-reza-rahman** [eclipse/microprofile-marketing#922]
I think we can put this on MicroProfile social media: https://groups.google.com/g/microprofile/c/9IXZG_BnUcs/m/ZA71HWtNAQAJ.

**Comment by rstjames** [comment]
@m-reza-rahman sorry I missed this... Is there a point to still do it?

**Comment by m-reza-rahman** [comment]
Nope. Closing.
