### ISSUE TITLE
May 21st 2024 MicroProfile Technical Meeting video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#925]
Here is the [link to the video](https://drive.proton.me/urls/PB8HFV0N5R#aAXLrqJnOVp7) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1hzEhePFbZ_9d5Nm-DdK-Coilm1J309GH82Yb8_hgB50/edit#bookmark=kix.ket0oykowqmi) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
Updated https://youtu.be/xS-4lfBVcJY
