### ISSUE TITLE
Website menu restructure 

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#927]
We need to restructure our website menu. 
Topics to discuss/ suggestions:
- We will add "Specification" pages ( we will need to create an ALL specification page.) 
-  Move blog to resources
- Projects page content is broken. What should we do with this page? 

Please share what changes you may suggest

**Comment by aeiras** [comment]
Discussed on the Monday marketing meeting, feedback requested on that discussion during the community call, Tuesday:

My recommendations:

1.  Move Projects' tab under Resources tab
2. Add Specifications where Projects' tab is now
3. create a landing page to house all Spec
4. each spec needs a landing page (git issue), using David's feedback here https://github.com/eclipse/microprofile-marketing/issues/828


--- @rstjames :)
