### ISSUE TITLE
June 10th 2024 MicroProfile AI video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#928]
Here is the [link to the video](https://drive.proton.me/urls/VWKK4T17BW#LU5Kerjp5BgH) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/14kSPRzEb0_BXrow1ej7Z6cus23uWypR_NcoegimJaBA/edit#bookmark=id.z9qjuap0n6vo) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://youtu.be/zJ8q86ssSN8 done
