### ISSUE TITLE
Jan 10th 2024 MicroProfile Marketing video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#929]
Here is the [link to the video](https://drive.proton.me/urls/HQT94PBDN4#wtdtxJv4t7J6) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1IEuuIowvv5epov_rNLva51IjRMgUGlbfPi-lInecJRI/edit#bookmark=kix.pqm7bkh09ygd) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://youtu.be/fT5pHddNkXc updated
