### ISSUE TITLE
June 11th 2024 MicroProfile Live Hangout video for Youtube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#930]
Here is the [link to the video](https://drive.proton.me/urls/SRG8HPERJ4#tgViQHeVoiRt) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/169CiDbekplRdmoerMQyEPxMVijJGP7OYM5wYDUbF4yw/edit#bookmark=kix.z7ui52jkw2wq) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://youtu.be/_GT-yXaH7gY Updated
