### ISSUE TITLE
CloudLand 2024 - MicroProfile workshop

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-marketing#931]
**[MP DevRel Branding Resources Community Support](https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support)**

**MicroProfiler**
Name Emily Jiang
Twitter ID or Github ID: @emilyfhjiang
Picture, nice to have

**Event**
Link to the event/conference/Session
Organizer logo,  nice to have
[CloudLand 2024](https://www.cloudland.org/en/home/)
https://my.doag.org/events/cloudland/2024/agenda/#eventDay.1718920800

https://my.doag.org/events/cloudland/2024/agenda/#agendaId.4183

**Schedule**
Day
Time
Friday 21.06.2024 | 12:00 - 14:45 | Nordcloud Lounge

**Media Description**
280 chararters
includes the Twitter ID of the Organizers & the name or Twitter ID of the speaker
Do you want to learn both Restful and Reactive microservices in one session? Our #javachampion @emilyfhjiang 
 will run a workshop using @MicroProfileIO at https://www.cloudland.org/en/home/
 on Friday 21.06.2024 | 12:00 - 14:45 | Nordcloud Lounge. Don't miss out!

**Design Card** (for MicroProfile designer)
Minimal requirements highlight the MicroProfiler & the Organizers

**Notes**
To help with everything

**Comment by rstjames** [comment]
![microprofile_doag_emily-workshop_2](https://github.com/eclipse/microprofile-marketing/assets/12132146/4b42af77-9802-4d02-bc38-7d4d9ccbc4ec)
Scheduled for two days

**Comment by Emily-Jiang** [comment]
@rstjames the time changed for my workshop to give the attendees some lunch :)

Friday 21.06.2024 | 10:00 - 12:45 | Nordcloud Lounge

Can you update the scheduled tweets? Thanks

**Comment by rstjames** [comment]
All updated @Emily-Jiang
