### ISSUE TITLE
Telemetry Specifications page

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#932]
Please go to this doc and fill in the needed information to create each page.
https://docs.google.com/document/d/1RPJB9JyFvnbmme1f2s52jrprronR--9Vp9RBDQfRYQs/edit#heading=h.4kitmexapqcp

**Comment by rstjames** [comment]
Please review and leave screenshots and comments here:
https://microprofile.io/specifications/telemetry/
Pass: MPreview

**Comment by Emily-Jiang** [comment]
Looks good, thanks @rstjames

**Comment by Emily-Jiang** [comment]
This is a comment applicable to all of the pages. We are working on the different versions. I am wondering how to differentiate this. I think we should do something like this:
<img width="614" alt="image" src="https://github.com/user-attachments/assets/0cf94e05-1b9a-4b7f-bf7c-44ad133d3ccf">

**Comment by rstjames** [comment]
We discussed this before and said we would not make versions on all separate pages. This topic needs a bigger discussion to understand the amount of work behind it and see what others think.

**Comment by Emily-Jiang** [comment]
> We discussed this before and said we would not make versions on all separate pages. This topic needs a bigger discussion to understand the amount of work behind it and see what others think.

We will only do the current versions and future versions but not going back to the old versions. The page should say which version is about. At the moment, it talks about a particular version. The title should say that version. When MP Telemetry 2.1 is release, a new page will be created. Then you will have 2 MP Telemetry pages. We can discuss next Monday at the marketing call.

**Comment by rstjames** [comment]
For review:  
https://microprofile.io/specifications/telemetry/
Password: MPreview

What I need are links to git for old versions

@Emily-Jiang @jclingan @edbratt @aeiras

**Comment by Emily-Jiang** [comment]
https://github.com/eclipse/microprofile-telemetry/releases/tag/1.0
https://github.com/eclipse/microprofile-telemetry/releases/tag/1.1
https://github.com/eclipse/microprofile-telemetry/releases/tag/2.0

**Comment by rstjames** [comment]
Updated
