### ISSUE TITLE
Open API  Specifications page

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#933]
Please go to this doc and fill in the needed information to create each page.

https://docs.google.com/document/d/1garDfQBtNentCW0CVUQNWiOfG_yqyHb_jRjJRdM-ksY/edit#heading=h.4kitmexapqcp

**Comment by Azquelt** [comment]
I have filled in the doc. Please let me know if there are any mistakes or anything that needs clarified.

**Comment by rstjames** [comment]
@Azquelt please review the page and let me know if I missed anything. If there are issues, please screenshot and comment here. 
https://microprofile.io/specifications/open-api/
pass: MPreview

**Comment by Emily-Jiang** [comment]
@rstjames the release review ballot was incorrect. The content is [here](https://www.eclipse.org/lists/microprofile-wg/msg02582.html). I also added a comment to the doc.

**Comment by Azquelt** [comment]
1. Sorry about the incorrect ballot results, I had copied from the wrong thread on the mailing list, thanks for catching that.
    
    It looks like the totals in the table were wrong on the original e-mail though, I think it should be
    
    ```
    Binding total: 8
    Non-binding votes: 1
    Binding + non-binding total: 9
    ```

2. The Smallrye OpenAPI certification is missing from the page - I see this is noted in the google doc.

3. The yellow text on a white or light grey background is hard to read - though this is a problem across the whole microprofile site.

Otherwise I think the content is fine :+1:

**Comment by rstjames** [comment]
@Azquelt @Emily-Jiang 
1. The ballet should be up to date now. 
2. I put a note in the doc on how we should show " Smallrye OpenAPI certification " when it is not on the "compatible pages." 
3. Not something we can solve right now.

**Comment by rstjames** [comment]
For review:  
https://microprofile.io/specifications/api/
Password: MPreview

What I need are links to git for old versions

@Emily-Jiang @jclingan @edbratt @aeiras

**Comment by Azquelt** [comment]
@rstjames Is the link correct? I get a 404.

I'm not sure what you mean by "links to git for old versions", are you looking for the MP OpenAPI github [releases page](https://github.com/eclipse/microprofile-open-api/releases)?

Each release is a git tag, so you can navigate from there to the code used for that release (e.g. [4.0 is here](https://github.com/eclipse/microprofile-open-api/tree/4.0)). Each release page also has links to the spec and javadoc for that version.

**Comment by rstjames** [comment]
@Azquelt sorry about that here is the correct link: 
https://microprofile.io/specifications/open-api/

**Comment by Emily-Jiang** [comment]
> For review: https://microprofile.io/specifications/api/ Password: MPreview
> 
> What I need are links to git for old versions
> 
> @Emily-Jiang @jclingan @edbratt @aeiras

https://github.com/eclipse/microprofile-open-api/releases/tag/1.0.1
https://github.com/eclipse/microprofile-open-api/releases/tag/1.1.3
https://github.com/eclipse/microprofile-open-api/releases/tag/1.2
https://github.com/eclipse/microprofile-open-api/releases/tag/2.0.1
https://github.com/eclipse/microprofile-open-api/releases/tag/3.0
https://github.com/eclipse/microprofile-open-api/releases/tag/3.1.2
https://github.com/eclipse/microprofile-open-api/releases/tag/4.0.1

**Comment by rstjames** [comment]
updated
