### ISSUE TITLE
Rest Client Specification page

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#934]
Please go to this doc and fill in the needed information to create each page.
https://docs.google.com/document/d/1LibXZLR4BpvHN7EoTytFKkXbq5NeIQkf06Lt1Hl4F5A/edit#heading=h.4kitmexapqcp

**Comment by rstjames** [comment]
@jclingan @Emily-Jiang please review and leave comments here with screenshots if there are issues. 
https://microprofile.io/specifications/rest-client/
Pass MPreview

I left a comment in the doc for @Emily-Jiang

**Comment by Emily-Jiang** [comment]
@rstjames the release review ballot info was incorrect. The correct one is [here](https://www.eclipse.org/lists/microprofile-wg/msg02581.html)

**Comment by rstjames** [comment]
check if correct now @Emily-Jiang

**Comment by Emily-Jiang** [comment]
> check if correct now @Emily-Jiang

Nope. It was not updated. Also see my other comments, all of the spec pages need to have the version listed.

**Comment by rstjames** [comment]
@Emily-Jiang my reply was a response to you saying the "ballot info was incorrect."

**Comment by Emily-Jiang** [comment]
@rstjames The page still shows the wrong ballot info for Plan Review and Release Review. You can find the ballot results from [this](https://github.com/microprofile/microprofile-wg/tree/main/rest-client/4.0#ballots) page.

**Comment by rstjames** [comment]
@Emily-Jiang ok hope its updated

**Comment by rstjames** [comment]
For review:  
https://microprofile.io/specifications/rest-client/
Password: MPreview

What I need are links to git for old versions

@Emily-Jiang @jclingan @edbratt @aeiras

**Comment by Emily-Jiang** [comment]
https://github.com/eclipse/microprofile-rest-client/releases/tag/1.0.1
https://github.com/eclipse/microprofile-rest-client/releases/tag/1.1
https://github.com/eclipse/microprofile-rest-client/releases/tag/1.2.1
https://github.com/eclipse/microprofile-rest-client/releases/tag/1.3.4
https://github.com/eclipse/microprofile-rest-client/releases/tag/1.4.1
https://github.com/eclipse/microprofile-rest-client/releases/tag/2.0
https://github.com/eclipse/microprofile-rest-client/releases/tag/3.0.1
https://github.com/eclipse/microprofile-rest-client/releases/tag/4.0

**Comment by rstjames** [comment]
Updated
