### ISSUE TITLE
Config Specifications page

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#935]
Please go to this doc and fill in the needed information to create each page.

https://docs.google.com/document/d/149Q6mq1LKo44xamG6cwHGqxZ9e-OtVVeJnoz-mgQNxc/edit#heading=h.4kitmexapqcp

**Comment by rstjames** [comment]
https://docs.google.com/document/d/1gyKddC9zHZ9UGXMn15mNWgH1lVzJ0psEY31P44GPCxQ/edit#heading=h.4kitmexapqcp @Emily-Jiang

**Comment by Emily-Jiang** [comment]
@rstjames done

**Comment by rstjames** [comment]
@Emily-Jiang please review and leave comments iwth screenshots here 
https://microprofile.io/specifications/config/
Pass: MPreview

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang please review and leave comments iwth screenshots here https://microprofile.io/specifications/config/ Pass: MPreview

@rstjames I got 404

**Comment by rstjames** [comment]
should be fixed  @Emily-Jiang

**Comment by Emily-Jiang** [comment]
> should be fixed @Emily-Jiang

still 404 @rstjames

**Comment by rstjames** [comment]
@Emily-Jiang pages has been published. try again

**Comment by Emily-Jiang** [comment]
I can see the page now. thanks! This page needs to say MicroProfile Config 3.1 on the title. Also in the compatible product list, Helidon needs to be added (see [here](https://microprofile.io/compatible/6-1/#) for more details. We need to work out a strategy how to keep them sync)

**Comment by rstjames** [comment]
OK updated. @Emily-Jiang

**Comment by rstjames** [comment]
For review:  
https://microprofile.io/specifications/config/
Password: MPreview

What I need are links to git for old versions

@Emily-Jiang @jclingan @edbratt @aeiras

**Comment by Emily-Jiang** [comment]
> For review: https://microprofile.io/specifications/config/ Password: MPreview
> 
> What I need are links to git for old versions
> 
> @Emily-Jiang @jclingan @edbratt @aeiras

https://github.com/eclipse/microprofile-config/releases/tag/1.0
https://github.com/eclipse/microprofile-config/releases/tag/1.1
https://github.com/eclipse/microprofile-config/releases/tag/1.2.1
https://github.com/eclipse/microprofile-config/releases/tag/1.3
https://github.com/eclipse/microprofile-config/releases/tag/1.4
https://github.com/eclipse/microprofile-config/releases/tag/2.0.1
https://github.com/eclipse/microprofile-config/releases/tag/3.0.3
https://github.com/eclipse/microprofile-config/releases/tag/3.1

**Comment by rstjames** [comment]
Updated
