### ISSUE TITLE
Fault Tolerance Specifications page

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#936]
Please go to this doc and fill in the needed information to create each page.
https://docs.google.com/document/d/1tFhT1inI2G3PdU2QawmCexc5aUmK8E9ZHgpqCZ_KFAE/edit#heading=h.4kitmexapqcp

**Comment by rstjames** [comment]
I updated the page on WP> Please review all links and content and put comments here with screenshots: 
https://microprofile.io/specifications/fault-tolerance/
password: MPreview

@Emily-Jiang

**Comment by Emily-Jiang** [comment]
The content looks good. For the title, can you update to MicroProfile Fault Tolerance 4.1?

**Comment by rstjames** [comment]
@Emily-Jiang why would we put 4.1 when no other pages have versions?

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang why would we put 4.1 when no other pages have versions?

@rstjames all of the other pages need to have versions.

**Comment by rstjames** [comment]
For review:  
https://microprofile.io/specifications/fault-talerance/
Password: MPreview

What I need are links to git for old versions

@Emily-Jiang @jclingan @edbratt @aeiras

**Comment by Emily-Jiang** [comment]
> For review: https://microprofile.io/specifications/fault-talerance/ Password: MPreview
> 
> What I need are links to git for old versions
> 
> @Emily-Jiang @jclingan @edbratt @aeiras

https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/1.0
https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/1.1.4
https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/2.0.4
https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/2.1.1
https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/3.0
https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/4.0.2
https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/4.1

**Comment by rstjames** [comment]
Updated
