### ISSUE TITLE
Metrics Specifications page

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#937]
Please go to this doc and fill in the needed information to create each page.

https://docs.google.com/document/d/1DB1CGxX-FbWz9JxaUF9n4X6RdGL0VbgI_buJldP77HU/edit#heading=h.4kitmexapqcp

**Comment by rstjames** [comment]
Doc not filled in @Emily-Jiang @jclingan

**Comment by Emily-Jiang** [comment]
@rstjames what you have in the doc as an example is correct for MP Metrics 5.1. Please just use that info.

**Comment by rstjames** [comment]
@Emily-Jiang I am looking at the doc link in this ticket and the doc is not filled out.

**Comment by rstjames** [comment]
@Emily-Jiang

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang

@rstjames we have done that one already. It was in the example. Scroll to the page 2. You don't need to recreate the page.

**Comment by rstjames** [comment]
For review:  
https://microprofile.io/specifications/metrics/
Password: MPreview

What I need are links to git for old versions

@Emily-Jiang @jclingan @edbratt @aeiras

**Comment by Emily-Jiang** [comment]
https://github.com/eclipse/microprofile-metrics/releases/tag/1.0.2
https://github.com/eclipse/microprofile-metrics/releases/tag/1.1.5
https://github.com/eclipse/microprofile-metrics/releases/tag/2.0.6
https://github.com/eclipse/microprofile-metrics/releases/tag/2.1.0
https://github.com/eclipse/microprofile-metrics/releases/tag/2.2.4
https://github.com/eclipse/microprofile-metrics/releases/tag/2.3.4
https://github.com/eclipse/microprofile-metrics/releases/tag/3.0.1
https://github.com/eclipse/microprofile-metrics/releases/tag/4.0.1
https://github.com/eclipse/microprofile-metrics/releases/tag/5.0.2
https://github.com/eclipse/microprofile-metrics/releases/tag/5.1.1

**Comment by rstjames** [comment]
Updated
