### ISSUE TITLE
JWT Auth Specifications page

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#938]
Please go to this doc and fill in the needed information to create each page.
https://docs.google.com/document/d/1jbX8VyDNwHJNb877EyjVC7Qo-FeZ5LsvUvjeHVBM2rk/edit#heading=h.4kitmexapqcp

**Comment by rstjames** [comment]
@Emily-Jiang try this to review: https://microprofile.io/specifications/jwt/
pass: MPreview

**Comment by cesarhernandezgt** [comment]
Hi @rstjames ,
I'm catching up with this pages, what is the process for example to see if implementations like https://github.com/apache/geronimo-jwt-auth can be added into the list?

**Comment by rstjames** [comment]
@Emily-Jiang please read cesars message above

**Comment by Emily-Jiang** [comment]
> Hi @rstjames , I'm catching up with this pages, what is the process for example to see if implementations like https://github.com/apache/geronimo-jwt-auth can be added into the list?

@cesarhernandezgt you will need to write the tck and file a CCR (see an example [here](https://github.com/eclipse/microprofile-jwt-auth/issues/269)).

**Comment by rstjames** [comment]
For review:  
https://microprofile.io/specifications/jwt/
Password: MPreview

What I need are links to git for old versions

@Emily-Jiang @jclingan @edbratt @aeiras

**Comment by Emily-Jiang** [comment]
> For review: https://microprofile.io/specifications/jwt/ Password: MPreview
> 
> What I need are links to git for old versions
> 
> @Emily-Jiang @jclingan @edbratt @aeiras

The links to the releases:
https://github.com/eclipse/microprofile-jwt-auth/releases/tag/1.0
https://github.com/eclipse/microprofile-jwt-auth/releases/tag/1.1.1
https://github.com/eclipse/microprofile-jwt-auth/releases/tag/1.2.2
https://github.com/eclipse/microprofile-jwt-auth/releases/tag/2.0
https://github.com/eclipse/microprofile-jwt-auth/releases/tag/2.1

**Comment by rstjames** [comment]
Updated
