### ISSUE TITLE
Health Specifications page 

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#939]
Please go to this doc and fill in the needed information to create each page.
https://docs.google.com/document/d/1DpBEpd8fEzaOsvr6HndwYwu1jzFSphiefZNAMxp2Gs4/edit#heading=h.4kitmexapqcp

**Comment by rstjames** [comment]
Here is a doc to fill in for content: https://docs.google.com/document/d/1DpBEpd8fEzaOsvr6HndwYwu1jzFSphiefZNAMxp2Gs4/edit#heading=h.4kitmexapqcp

**Comment by rstjames** [comment]
@jclingan Please review and leave screenshots with comments. Some info might be missing if it was not supplied: 
https://microprofile.io/specifications/health/
Pass: MPreview

**Comment by Emily-Jiang** [comment]
@rstjames the maven coordinates were wrong. It shows JWT. Please get the snippet from the Health doc. Also, the page does not list the compatible products.

**Comment by rstjames** [comment]
maven coordinates fixed

**Comment by Emily-Jiang** [comment]
Looks good.

**Comment by xstefank** [comment]
It now shows rest-client coordinates in the preview, should be:

```
<dependency>
    <groupId>org.eclipse.microprofile.health</groupId>
    <artifactId>microprofile-health-api</artifactId>
    <version>4.0</version>
</dependency>
```

**Comment by xstefank** [comment]
@rstjames also probably this is also coming from REST client, we have only one mandatory TCK in Health.

![2024-09-13-1726210833_261x146](https://github.com/user-attachments/assets/1a70045c-fde0-4b81-bb00-e6cd4e606e9b)

**Comment by rstjames** [comment]
updated

**Comment by rstjames** [comment]
For review:  
https://microprofile.io/specifications/health/
Password: MPreview

What I need are links to git for old versions

@Emily-Jiang @jclingan @edbratt @aeiras

**Comment by rstjames** [comment]
@xstefank  please review and provided the missing links for older version thanks

**Comment by Emily-Jiang** [comment]
> For review: https://microprofile.io/specifications/health/ Password: MPreview
> 
> What I need are links to git for old versions
> 
> @Emily-Jiang @jclingan @edbratt @aeiras

@rstjames 
The links for each releases. The release version is the digits after the `tag`
https://github.com/eclipse/microprofile-health/releases/tag/1.0
https://github.com/eclipse/microprofile-health/releases/tag/2.0.1
https://github.com/eclipse/microprofile-health/releases/tag/2.1
https://github.com/eclipse/microprofile-health/releases/tag/2.2
https://github.com/eclipse/microprofile-health/releases/tag/3.0
https://github.com/eclipse/microprofile-health/releases/tag/3.1
https://github.com/eclipse/microprofile-health/releases/tag/4.0.1

**Comment by rstjames** [comment]
Updated

**Comment by xstefank** [comment]
@rstjames sorry, I missed the notification.

@Emily-Jiang thank you for filling this in.
