### ISSUE TITLE
June 18th 2024 MicroProfile Technical Meeting video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#942]
Here is the [link to the video](https://drive.proton.me/urls/GTWYEZ5QQM#ChlzxiNEBKyx) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1hzEhePFbZ_9d5Nm-DdK-Coilm1J309GH82Yb8_hgB50/edit#bookmark=kix.ix12vc9u55lo) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://youtu.be/ZoVKa8Qu_2I
