### ISSUE TITLE
June 25th 2024 MicroProfile Steering Committee video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#943]
Here is the [link to the video](https://drive.proton.me/urls/M7FAMTF6T0#bqlxzznkuyJA) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1Vd5AWzqc6nHB7GF8DhKoSiMzIQumqGtbL3yq1ISr8RU/edit#heading=h.hyh98usp6p0d) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://youtu.be/lJDLgTuA2Es
