### ISSUE TITLE
July 1st 2024 MicroProfile AI video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#944]
Here is the [link to the video](https://drive.proton.me/urls/1GJC2NFRT4#gkBOIT1KyXX5) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/14kSPRzEb0_BXrow1ej7Z6cus23uWypR_NcoegimJaBA/edit#bookmark=kix.64jyastqd1jm) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://youtu.be/mwntc8cwqQU
