### ISSUE TITLE
July 2nd 2024 MicroProfile Technical Meeting video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#946]
Here is the [link to the video](https://drive.proton.me/urls/1YVWE97D1W#Ia9i32A3hdF9) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1hzEhePFbZ_9d5Nm-DdK-Coilm1J309GH82Yb8_hgB50/edit#bookmark=kix.4rgmlov94qzk) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://youtu.be/rZVwBn11aH8 updated
