### ISSUE TITLE
[MPWG Releases] Announcement Blog - MicroProfile 7.0

### ISSUE THREAD

**Issue by pedanticdev** [eclipse/microprofile-marketing#949]
Create the release announcement blog for MP 7.0 based on the [specification](https://download.eclipse.org/microprofile/microprofile-7.0-RC1/microprofile-spec-7.0-RC1.pdf).

**Comment by pedanticdev** [comment]
Hi @Emily-Jiang could you please do a first quick review of the blog and PPT in the[ requisite folder](https://drive.google.com/drive/folders/1tuyJ1VA-KpJ3mWw5-w3HBUl5s5mTGqPy?usp=sharing)? Thanks.

**Comment by penta-luqman** [comment]
Ping @Emily-Jiang. Maybe @rstjames you could also take a look. Thanks.

**Comment by pedanticdev** [comment]
Ping @Emily-Jiang . Maybe @rstjames you could also take a look. Thanks.

**Comment by pedanticdev** [comment]
@Emily-Jiang  should we maintain the [blog template](https://drive.google.com/drive/u/0/folders/0B8_67yGf9LkLX096QUdxcTdueWs?resourcekey=0-zCVjDPtS441ppquRx4Xkpg) for future blogs or leave it? I used the 6.1 blog you composed as the basis for the 7.0 one. If we don't need the template, then we can ignore it.

**Comment by rstjames** [comment]
Done and scheduled
