### ISSUE TITLE
July 23rd 2024 MicroProfile Live Hangout video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#950]
Here is the [link to the video](https://drive.proton.me/urls/R079AYYPBM#2hzzaK2xT4wd) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/169CiDbekplRdmoerMQyEPxMVijJGP7OYM5wYDUbF4yw/edit#bookmark=kix.dq3xouk75wo9) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
Updated
