### ISSUE TITLE
July 30th 2024 MicroProfile Technical Call video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#952]
Here is the [link to the video](https://drive.proton.me/urls/GHFCC5790G#XcCkafdm4nW1) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1hzEhePFbZ_9d5Nm-DdK-Coilm1J309GH82Yb8_hgB50/edit#bookmark=id.edn3h0rjh47m) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
Updated
