### ISSUE TITLE
August 5th 2024 MicroProfile Marketing Meeting video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#953]
Here is the [link to the video](https://drive.proton.me/urls/H466GGRDNR#BauxRhpTbWLx) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1IEuuIowvv5epov_rNLva51IjRMgUGlbfPi-lInecJRI/edit#bookmark=kix.mxe12otgf7) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
Updated
