### ISSUE TITLE
[Compatible Implementations Announcement] Helidon 4

### ISSUE THREAD

**Issue by edbratt** [eclipse/microprofile-marketing#956]
**Organization Name**
 Name: Oracle Corporation
 
 **Product Name, Version and download URL (if applicable)**
 Product Name: Helidon
Version: 4
URL: https://helidon.io
 
 **Link to CCR (GH issue in the eclipse/microprofile repository)**
 Link: https://github.com/eclipse/microprofile/issues/422
 
**Update the compatible page with the following info**
Product Name: Helidon 4
Java Version: Java 21 or higher
Certification Results: [MicroProfile #422](https://github.com/eclipse/microprofile/issues/422)
Download: https://helidon.io

 **Media Description**
We are pleased to announce Helidon 4 as a certified compatible implementation of MicroProfile 6. Please browse to https://helidon.io and click on the 'Starter' button to begin working with Helidon today.

 **Design Card**  (for MicroProfile designer)
Please see the attached product zip for product icon/image.
[Helidon-frank-profile-RGB.zip](https://github.com/user-attachments/files/16566738/Helidon-frank-profile-RGB.zip)

 **Notes**
Use the attached image for the Compatible Implementations 6.0 page.

**Comment by rstjames** [comment]
@edbratt what version is this for? 6.1?

**Comment by edbratt** [comment]
Yes, MicroProfile 6.1

**Comment by rstjames** [comment]
all set and scheduled
![microprofile_helidon-4_compatible_6 1](https://github.com/user-attachments/assets/5410190f-cafd-4b3c-a21a-ca62c3f4e53e)

**Comment by edbratt** [comment]
Ryan, the CCR I submitted is for MicroProfile 6.0. Not 6.1. While saying that we are just about to submit a CCR for MicroProfile 6.1 so, I guess you can decide if you want to leave this alone, or update it for 6.0. In any case, the 6.1 certification will be for Helidon 4.1, but all the access links, etc. will be the same.  The new CCR will be up this week.

**Comment by rstjames** [comment]
@edbratt ok sorry for the mistake. but the message above, you confirmed 6.1.  

I will remove these sections and add it to 6.0

**Comment by edbratt** [comment]
My Bad. Sorry. Probably I was focused on the new certification. Anyway, 6.0 for now.

**Comment by rstjames** [comment]
Updated on fb and LinkedIn. I dont have access to Twitter right now.

**Comment by rstjames** [comment]
![microprofile_helidon-4_compatible_6 0](https://github.com/user-attachments/assets/54e674e2-7af8-4e29-b2b0-5c1399ab2858)
