### ISSUE TITLE
Broken link, MicroProfile Compatible Implementations page

### ISSUE THREAD

**Issue by edbratt** [eclipse/microprofile-marketing#957]
The link on https://microprofile.io/compatible/ for 'Implementation Certification Process' points to wiki.eclipse.org which no longer exists. The newest archive.org capture I could find was from May 2023. https://web.archive.org/web/20230201165902/https://wiki.eclipse.org/Implementation_Certification_Process
If a replacement page exists, please just fix the link. Otherwise, we will need a new info. page as well.

**Comment by rstjames** [comment]
@edbratt is there a reason why this page doesnt exist anymore? We can make our own page on our site but I will need some conent for that page. 
@jclingan thoughts on this?
