### ISSUE TITLE
August 13th 2024 MicroProfile Technical Meeting video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#958]
Here is the [link to the video](https://drive.proton.me/urls/9RSN23PVBM#7xOps2Jp9Pbg) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1hzEhePFbZ_9d5Nm-DdK-Coilm1J309GH82Yb8_hgB50/edit#bookmark=id.ejzf8d9guyoz) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
uploaded and updated
