### ISSUE TITLE
August 19th 2024 MicroProfile AI Meeting video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#959]
Here is the [link to the video](https://drive.proton.me/urls/DZFX7MJKSM#U1h08xHIsOVR) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/14kSPRzEb0_BXrow1ej7Z6cus23uWypR_NcoegimJaBA/edit#bookmark=kix.p5o6brbwgbz8) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
uploaded and updated link on doc
