### ISSUE TITLE
August 19th 2024 MicroProfile Marketing Meeting video

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#960]
Here is the [link to the video](https://drive.proton.me/urls/6VNZDBD5PG#vyaotHuYdeTv) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1IEuuIowvv5epov_rNLva51IjRMgUGlbfPi-lInecJRI/edit#bookmark=kix.wqnl415px9zk
) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
uploaded and doc updated
