### ISSUE TITLE
      MicroProfile 7.0 Release Blog 

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#962]

**Comment by Emily-Jiang** [comment]
Blog [here](https://docs.google.com/document/d/10gzLTZDU4Q4eNaKwiqB8jlqjIOLMgnFyWcRfW8nb9VQ/edit)

**Comment by aeiras** [comment]
@Emily-Jiang the content is not in the MP drive, so I cannot review it. Please move it. Cheers.

**Comment by Emily-Jiang** [comment]
It is in the [drive](https://drive.google.com/drive/folders/1tuyJ1VA-KpJ3mWw5-w3HBUl5s5mTGqPy)

**Comment by aeiras** [comment]
Thank you. Feedback provided via suggested edit. :)

**Comment by rstjames** [comment]
https://microprofile.io/2024/08/22/microprofile-7-0-release/
