### ISSUE TITLE
MicroProfile 7.0 Compatible webpage

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#963]
What is needed: 
- specification box image
- MP7 description 
- Compatible Implementations for MicroProfile 7 - @Emily-Jiang I will need this content
- Blog post update

I created a draft page already and will add these sections when the correct info is put in this ticket. @Emily-Jiang

**Comment by Emily-Jiang** [comment]
Compatible page:
Open Liberty - [24.0.0.9-beta-cl240920240801-0303](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/tck/2024-08-01_0303/openliberty-24.0.0.9-beta-cl240920240801-0303.zip)
Java version: Java 11, 17 and 21
Links: [Certification Results  ](https://openliberty.io/certifications/microprofile/7.0/24.0.0.9-beta-cl240920240801-0303-TCKResults.html) [Download](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/tck/2024-08-01_0303/openliberty-24.0.0.9-beta-cl240920240801-0303.zip)

**Comment by Emily-Jiang** [comment]
Blog is [here](https://docs.google.com/document/d/10gzLTZDU4Q4eNaKwiqB8jlqjIOLMgnFyWcRfW8nb9VQ/edit)
Specification Box image: [here](https://docs.google.com/presentation/d/1gg67Gv38B8QJ9o0u_pwoiQf3NvigB_MgL7ZgabL_I2U/edit#slide=id.p8)
MP 7.0 description: 
MicroProfile 7.0 does not packages Jakarta EE 10 Core Profile. Instead, it specifies the dependency on Jakarta EE 10 Core Profile. This release does not include MicroProfile Metrics, as MicroProfile Telemetry 2.0 offers the Metrics capabilities in addition to Logs and Tracing. There are 4 updated specifications: Telemetry 2.0, Fault Tolerance 4.1, Open API 4.0 and Rest Client 4.0 while Config, Health and JWT Authentication remain unchanged from the MicroProfile 6.1.

**Comment by rstjames** [comment]
done
