### ISSUE TITLE
MicroProfile 7 Release Social Media

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#964]
We need: 
- SM message for release
- Image for release

These messages will connect to the release blog post

**Comment by pedanticdev** [comment]
### Option 1

🎉 **MicroProfile 7.0 is here!** 🎉

We've just released a major update, making MicroProfile even better for building Java microservices. This version brings exciting new features, including enhanced telemetry capabilities.

**Key Highlights:**

* **MicroProfile Telemetry 2.0:** Get deeper insights with comprehensive metrics, logs, and tracing.
* **Jakarta EE 10 Core Profile:** Now a dependency for better integration.

Ready to get started? Visit the MicroProfile website for more details and start building amazing microservices today! 

#MicroProfile #Java #Microservices



### Option 2

🚀 **MicroProfile 7.0 is taking off!** 🚀

Upgrade your Java microservices with the latest MicroProfile release. We've packed in improvements like advanced telemetry capabilities and tighter Jakarta EE integration. Get ready to build cloud-native apps that are easier to monitor and manage.

Check out the details on the MicroProfile website and start building!

#MicroProfile #Java #Microservices #CloudNative


### Option 3


🎉 **The future of Java microservices is here!** 🎉

We're thrilled to announce the release of MicroProfile 7.0. This major update brings exciting new features, including enhanced telemetry capabilities and seamless integration with Jakarta EE. 

Explore the possibilities on the MicroProfile website and start building the next generation of microservices today!

#MicroProfile #Java #Microservices #Innovation

**Comment by Emily-Jiang** [comment]
Option 1 is good for LinkedIn post but too long for X. Option 3 might be good for X. Can we use different variants for different social medias @rstjames ?

**Comment by rstjames** [comment]
yep not a problem

**Comment by jclingan** [comment]
TBH, they all look good. I like option 1 for the longer format and option 3 for the shorter format.

**Comment by rstjames** [comment]
done
![microprofile_7_release](https://github.com/user-attachments/assets/b37b33ca-de02-451e-b65e-9e109a90fc0c)
