### ISSUE TITLE
MicroProfile 7.0 Compatible annoucement

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#965]
This will need a card: 
- message for release
- image
- Content for website

**Comment by pedanticdev** [comment]
By message do you mean the theme?

**Comment by pedanticdev** [comment]
What kind of content would be needed for the website outside the blog? Is there anything I can assist in that regards?

**Comment by aeiras** [comment]
@pedanticdev, 

Are you interested in becoming an admin to MP Hootsuite?  Do you know how to use the tool?  If so, please open a new ticket and assign it to me. title [Marketing INFRA tool access] Hootsuite - Payara Admin Access.   No pressure.  Helping with releases requires access to social media. Please consider it carefully and read the wiki on social media access first. https://github.com/eclipse/microprofile-marketing/wiki/Code-of-Conduct-Standards-for-Social-Media-Contribution

**Comment by penta-luqman** [comment]
I'd love to, but out of the abundance of caution, I'd rather we Ryan run things from Hootsuite for this release, after which I can request for the access, given the release is imminent. I can always help out on the tickets here and then Ryan can copy to HS.

**Comment by pedanticdev** [comment]
I'd love to, but out of the abundance of caution, I'd rather Ryan run things from Hootsuite for this release, after which I can request for the access, given the release is imminent. I can always help out on the tickets here and then Ryan can copy to HS.

**Comment by aeiras** [comment]
Very sensible response, Luqman. 
Let's calmly onboard you into Hootsuite after the MP 7 release. When you are ready, please submit the ticket, and I will provide access. Ryan will explain how MP Hootsuite navigation works.

**Comment by pedanticdev** [comment]
Sure will.

**Comment by rstjames** [comment]
done
![microprofile_7_compatible](https://github.com/user-attachments/assets/7e98f593-dc65-4ae3-8d8c-3b9aa436a9ae)
