### ISSUE TITLE
MicroProfile 7.0 Home page update

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#966]
<img width="1241" alt="Screenshot 2024-08-20 at 16 51 36" src="https://github.com/user-attachments/assets/022f5d41-93f5-4b71-94ca-62615eeeca6e">
<img width="497" alt="Screenshot 2024-08-20 at 16 51 30" src="https://github.com/user-attachments/assets/84020c71-4358-4e3a-8ab1-7c326881ef6d">

**Comment by pedanticdev** [comment]
Will this be extracted from the blog or we need separate copy? 

If a separate copy is needed then ... here we go ...

MicroProfile 7.0 is a major release that introduces significant changes, notably replacing MicroProfile Metrics with the more comprehensive MicroProfile Telemetry 2.0.  Additionally, it specifies Jakarta EE 10 Core Profile as a dependency, simplifying integration. This release also includes updates to several specifications, and allows certification on Java SE 11 and higher.

**Comment by rstjames** [comment]
done
