### ISSUE TITLE
[Compatible Implementations Announcement] Product Name, Version 

### ISSUE THREAD

**Issue by edbratt** [eclipse/microprofile-marketing#968]
Organization Name
Name: Oracle Corporation

Product Name, Version and download URL (if applicable)
Product Name: Helidon
Version: 4.1
URL: https://helidon.io/

Link to CCR (GH issue in the eclipse/microprofile repository)
Link: https://github.com/eclipse/microprofile/issues/467

Update the compatible page with the following info
Product Name: Helidon 4.1
Java Version: Java 21 or higher
Certification Results: https://github.com/eclipse/microprofile/issues/467 or https://github.com/helidon-io/helidon/wiki/MicroProfile-6.1-and-Jakarta-EE-10-Core-Profile-Certification,-Helidon-4.1
Download: https://helidon.io/

Media Description
We are pleased to announce Helidon 4.1 as a certified compatible implementation of MicroProfile 6.1. Please browse to https://helidon.io/ and click on the 'Starter' button to begin working with Helidon today.

Design Card (for MicroProfile designer)
Please see the attached product zip for product icon/image.
[Helidon-frank-profile-RGB.zip](https://github.com/user-attachments/files/16566738/Helidon-frank-profile-RGB.zip)

Notes
Use the attached image for the Compatible Implementations 6.0 page.

**Comment by rstjames** [comment]
Website update @edbratt 
Social scheduled 
![microprofile6 1_helidon_4 1_compatible](https://github.com/user-attachments/assets/de6efa2e-66e0-4d93-8770-1eee0674f2ff)
