### ISSUE TITLE
September 9th 2024 MicroProfile AI video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#969]
Here is the [link to the video](https://drive.proton.me/urls/7F2FAPG7QR#iIdb7L03sXJG) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/14kSPRzEb0_BXrow1ej7Z6cus23uWypR_NcoegimJaBA/edit#bookmark=kix.xhfl4wqseihs) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
updated
