### ISSUE TITLE
September 10th 2024 MicroProfile Technical Meeting video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#970]
Here is the [link to the video](https://drive.proton.me/urls/3A4MW8RVCW#iP1krwOATvdp) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1hzEhePFbZ_9d5Nm-DdK-Coilm1J309GH82Yb8_hgB50/edit#bookmark=kix.9xxag0ghe8i0) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
updated
