### ISSUE TITLE
[Docs] Adding a Section to  the WIKI: Committer Representative Role Description

### ISSUE THREAD

**Issue by emecas** [eclipse/microprofile-marketing#972]
New section is about: [Recurring seat/elections](https://github.com/microprofile/microprofile-wg/wiki/Committer-Representative-Role-Description#recurring-seatelections)

Changes: https://github.com/microprofile/microprofile-wg/wiki/Committer-Representative-Role-Description/_compare/5dcc5a0569ffb2014d51e612b30c3b17fa3f4d91...4fa415f647846bd06e39467d796ba3e905b6b659

Feedback is welcome!!

**Comment by aeiras** [comment]
It reads great @emecas. 

My only suggestion in the future is to add changes via a PR on wikis if you wish feedback to be given instead of reverting the changes.  Thankfully, there is no need to revert the improvements. :)
