### ISSUE TITLE
Contact Clark about MicroProfile OCX participation

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#973]
This is being covered in the [MicroProfile Marketing meetings](https://docs.google.com/document/d/1IEuuIowvv5epov_rNLva51IjRMgUGlbfPi-lInecJRI/edit#bookmark=id.c1vytyodt36b).

**Comment by rstjames** [comment]
https://github.com/eclipse/microprofile-marketing/issues/906#issuecomment-2254820958

based on the quotes + estimated shipping costs and taxes, I would estimate a total spend of around $5K.
Based on the MP revised budget of $10.5 K for discretionary spending, this leaves approximately $5.5K for 2024.

**Comment by rstjames** [comment]
Follow up on latest progress and opportunities for collaboration (probably with Clark and/or Paul).
The MicroProfile budget includes $2,500 for Eclipse events. Does this include OCX? Or does this require an additional budget?
Booth?
Logo placement?
Sponsorship includes?

**Comment by jclingan** [comment]
Also, are there any expectations of the MicroProfile Working Group?

**Comment by emecas** [comment]
To Do:  Mainly, follow up to clarify, these two points with Clark (EF):

- [x]  > Follow up on latest progress and opportunities for collaboration (probably with Clark and/or Paul). The MicroProfile budget includes $2,500 for Eclipse events. Does this include OCX? Or does this require an additional budget? Booth? Logo placement? Sponsorship includes?

- [x]  > Also, are there any expectations from the MicroProfile Working Group?

----
Updated  2024-09-18: Contacted Clark Roundy via email about the 2 subjects, waiting for his response (CC: Paul Buck and Sharon Corbett)

----
Updated  2024-09-23: Followed up to previous email from last week, I am still waiting for Clark's response (CC: Paul Buck and Sharon Corbett)

----
Updated  2024-09-24: Clark'd responded to the email and Sharon Corbett shared it on the MicroProfile Steering Committee email list

Summary: 

1)  

 Yes, The MicroProfile  2.5K event budget includes OCX:

>  - MicroProfile is prominently featured in the Open Community for Java (OCJ) co-located event. See reference [here](https://www.ocxconf.org/event/2024/websitePage:77f60b73-336c-43be-827d-8d8fcb1aaf64).
>  - MicroProfile is highlighted in the OCX Announcement [here](https://newsroom.eclipse.org/news/announcements/eclipse-foundation-unveils-open-community-experience-ocx-europe%E2%80%99s-premier-event) and [here](https://blogs.eclipse.org/post/clark-roundy/ocx-2024-celebrating-community-code-and-collaboration).
>  - At the event, MicroProfile will be highlighted in the Industry Collaboration Booth.  The MicroProfie logo will be on display in the booth as part of the Industry Collaboration portfolio and for which we will be using the opportunity to promote collaboration across pillars, working groups, and project communities.
>  - MicoProfile is also included in printed collateral for the Industry Collaborations booth, including stickers, visual presentations and pitch decks.  
>  - Eclipse Foundation leadership will actively promote Java related collaborations, including MicroProfile, at the booth.

2) 

Expectations from the MicroProfile Working Group:

 > Expectations for MicroProfile working group members, the primary request is simply to attend and participate. While participation in the Industry Collaborations booth is not mandatory, members are welcome to engage by being available to answer questions and promote their initiatives
