### ISSUE TITLE
Specifications home page

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#974]
We need to determine the content for the specification homepage, where all specs will be listed. It’s important to ensure the page scales efficiently so that we don’t have to redesign it every time a new spec is added. What key information should we include in the table? Each section should link to an overall spec page that lists the available versions, with further links to detailed pages for each version.

URL suggestion: 
www.microprofile.io/specification/openapi/version

Right now we have this as a base: 
![screencapture-microprofile-io-specifications-2024-09-17-16_18_09](https://github.com/user-attachments/assets/6147f76e-070d-4291-8d3a-7315a0950111)

**Comment by Emily-Jiang** [comment]
In this page, we should add column on versions. Once you click one particular version, you will go to the individual spec pages. Have a look at [this](https://jakarta.ee/specifications/) page. We should do the similar design.

**Comment by rstjames** [comment]
Not scalable. We will still need to create a project version page that lists all versions. 

What i need to know what info do we want on this table for all specs page. Listing the versions won't scale when there are a lot of versions unless we want to do this and remake it later so it scales. 

- Or will we need a "spec all-version" page. 
          - If so, we need to know what we want to show on this page (description, list of spec versions, blogs?, link to meeting schedule? 
          this means 10 more pages and we need to adjust the url structure. 
          
@Emily-Jiang @jclingan

**Comment by Emily-Jiang** [comment]
> Not scalable. We will still need to create a project version page that lists all versions.
> 
> What i need to know what info do we want on this table for all specs page. Listing the versions won't scale when there are a lot of versions unless we want to do this and remake it later so it scales.
> 
>     * Or will we need a "spec all-version" page.
>       - If so, we need to know what we want to show on this page (description, list of spec versions, blogs?, link to meeting schedule?
This works. That was one of my choices. We will show the list of spec versions, github repo to the spec, links to the meeting schedule if applicable.
>       this means 10 more pages and we need to adjust the url structure.
I thought about this, which is why I changed my idea to put the version in the top level. I guess if this is not scable. I am okay with the extra pages idea. It is a clear design.
> 
> 
> @Emily-Jiang @jclingan
