### ISSUE TITLE
September 16th 2024 MicroProfile Marketing video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#975]
Here is the [link to the video](https://drive.proton.me/urls/V5B44QFZAG#GiS8z7arsOc4) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1IEuuIowvv5epov_rNLva51IjRMgUGlbfPi-lInecJRI/edit#bookmark=kix.n3x1ju27mbm) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
updated
