### ISSUE TITLE
September 30th 2024 MicroProfile Marketing video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#976]
Here is the [link to the video](https://drive.proton.me/urls/AN159KGWYW#dqH1gzEQsrYx) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1IEuuIowvv5epov_rNLva51IjRMgUGlbfPi-lInecJRI/edit#bookmark=kix.9mu5hav6utdj) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
updated
