### ISSUE TITLE
September 23rd 2024 MicroProfile AI video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#977]
Here is the [link to the video](https://drive.proton.me/urls/Q4MJ5WVTDR#h0xllHmgkP4e) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/14kSPRzEb0_BXrow1ej7Z6cus23uWypR_NcoegimJaBA/edit#bookmark=kix.1j2a5u2te95g) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
updated
