### ISSUE TITLE
Septembert 30th 2024 MicroProfile AI video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#978]
Here is the [link to the video](https://drive.proton.me/urls/QWWTGHDF4C#gMXoSPyUduIP) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/14kSPRzEb0_BXrow1ej7Z6cus23uWypR_NcoegimJaBA/edit#bookmark=kix.qoqazrc3x9ag) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
updated
