### ISSUE TITLE
September 17th 2024 MicroProfile Live Hangout video

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#979]
Here is the [link to the video](https://drive.proton.me/urls/YPTNS1J32W#8UL0AtVG39s8) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/169CiDbekplRdmoerMQyEPxMVijJGP7OYM5wYDUbF4yw/edit#bookmark=kix.mmmjn8dcp9fe) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
updated
