### ISSUE TITLE
September 24th 2024 MicroProfile Technical Meeting video

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#980]
Here is the [link to the video](https://drive.proton.me/urls/ZN6FVV6ZWW#cbilTwDX9jQN) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1hzEhePFbZ_9d5Nm-DdK-Coilm1J309GH82Yb8_hgB50/edit#bookmark=kix.jw9k1swoysan) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
updated
