### ISSUE TITLE
October 1st 2024 MicroProfile Steering Committee Meeting

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#982]
Here is the [link to the video](https://drive.proton.me/urls/081KN0SXTM#B0lPSyqmfoFA) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1iGWGdsr1xk176SYFo2SmNW851__1o1rlzu6V-_CMsMA/edit#bookmark=id.9chz6neppgq8) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
didnt have access for the notes. please add the recording link  @jclingan 
https://youtu.be/DhtDUTObz8k

**Comment by jclingan** [comment]
Shared doc, but I have already updated the meeting minutes with the link. Thanks!
