### ISSUE TITLE
October 14th 2024 MicroProfile AI video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#984]
Here is the [link to the video](https://drive.proton.me/urls/SWS2C0BQ7G#LnDzVtGRgNO3) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/14kSPRzEb0_BXrow1ej7Z6cus23uWypR_NcoegimJaBA/edit?tab=t.0#bookmark=kix.pb1afhybqhk7) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
Updated
