### ISSUE TITLE
[Website] Broken Link to Wiki MP Implementation List

### ISSUE THREAD

**Issue by emecas** [eclipse/microprofile-marketing#986]
From: MP website: 

https://microprofile.io/compatible/# 
or
https://microprofile.io/compatible/#about-text

By clicking the button `See Implementation List` that is pointing to: https://wiki.eclipse.org/MicroProfile/Implementation:\

![image](https://github.com/user-attachments/assets/75ca01ad-2062-48f8-883f-c1871191cb16)

It takes you to this broken link:

![image](https://github.com/user-attachments/assets/4f0d3634-bfe9-4347-ba15-1c12b55c9bf5)

**Comment by rstjames** [comment]
@emecas thank you for pointing this out. Where should it be pointing? 

Here? https://projects.eclipse.org/projects/technology.microprofile

**Comment by emecas** [comment]
@rstjames

That could be a good link to point if there is not a better option, let me explain myself, I was looking for information about which implementations were certified to what MicroProfile version(s), before MicroProfile 4.0

**Comment by rstjames** [comment]
ok, not sure @Emily-Jiang any ideas?

**Comment by Emily-Jiang** [comment]
Before MP 4.0, there was no certification. The `See Implementation List` should point to https://github.com/eclipse/microprofile/wiki/Implementation

**Comment by rstjames** [comment]
Updated
