### ISSUE TITLE
Update the building box on the release 7.0

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-marketing#987]
Since we have created the detailed spec pages, in the homepage of microprofile.io. Each box should point to the detailed spec page.

<img width="591" alt="image" src="https://github.com/user-attachments/assets/115bd161-7df4-438e-a79d-26c960c1027a">

e.g. Telemetry 2.0 should link to https://microprofile.io/specifications/telemetry/2-0/

**Comment by rstjames** [comment]
Updated on home and 7.0 page
