### ISSUE TITLE
Individual spec page

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-marketing#988]
The link on the right hand of the spec page should point to the detailed spec page:
<img width="1156" alt="image" src="https://github.com/user-attachments/assets/16bd19d1-141e-4aae-88be-6308f96a3349">

The `view` button for Config 3.1 should point to https://microprofile.io/specifications/config/3-1/

**Comment by Emily-Jiang** [comment]
All of the spec pages have the same issue @rstjames

**Comment by rstjames** [comment]
Updated
