### ISSUE TITLE
October 15th 2024 MicroProfile Live Hangout video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#990]
Here is the [link to the video](https://drive.proton.me/urls/M5AMK040MG#mcKrArfckn6b) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/169CiDbekplRdmoerMQyEPxMVijJGP7OYM5wYDUbF4yw/edit?tab=t.0#bookmark=kix.1kjsxiga299s) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
updated
