### ISSUE TITLE
October 22nd 2024 MicroProfile Technical Meeting video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#991]
Here is the [link to the video](https://drive.proton.me/urls/PBBMFJ2PMW#3LcO7MEZGd7I) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1hzEhePFbZ_9d5Nm-DdK-Coilm1J309GH82Yb8_hgB50/edit?tab=t.0#bookmark=id.n3pq6f2xwm3k) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
Updated
