### ISSUE TITLE
October 28th 2024 MicroProfile AI video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#996]
Here is the [link to the video](https://drive.proton.me/urls/N30GVWD8P8#xmIcgq4Lydy3) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/14kSPRzEb0_BXrow1ej7Z6cus23uWypR_NcoegimJaBA/edit?tab=t.0#bookmark=kix.pgjlfmgj37r1) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
done
