### ISSUE TITLE
November 5th 2024 MicroProfile Technical Meeting video for YouTube

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-marketing#998]
Here is the [link to the video](https://drive.proton.me/urls/WTH14GYRBR#I5ct9FvCPZjb) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1hzEhePFbZ_9d5Nm-DdK-Coilm1J309GH82Yb8_hgB50/edit?tab=t.0#bookmark=id.wrmfr9xul7b) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
done
